package com.bytecause.nautichart.util

// Geofabrik country's name mapping.
object CountryNameMapping {

    fun getCountryIso(name: String): String {
        val hashMap: HashMap<String, String> = HashMap()

        // Europe
        hashMap["Albania"] = "AL"
        hashMap["Andorra"] = "AD"
        hashMap["Austria"] = "AT"
        hashMap["Azores"] = "PT"
        hashMap["Belarus"] = "BY"
        hashMap["Belgium"] = "BE"
        hashMap["Bosnia-Herzegovina"] = "BA"
        hashMap["Bulgaria"] = "BG"
        hashMap["Croatia"] = "HR"
        hashMap["Cyprus"] = "CY"
        hashMap["Czech Republic"] = "CZ"
        hashMap["Denmark"] = "DK"
        hashMap["Estonia"] = "EE"
        hashMap["Faroe Islands"] = "FO"
        hashMap["Finland"] = "FI"
        hashMap["France"] = "FR"
        hashMap["Georgia"] = "GE"
        hashMap["Germany"] = "DE"
        hashMap["Greece"] = "GR"
        hashMap["Guernsey and Jersey"] = ""
        hashMap["Hungary"] = "HU"
        hashMap["Iceland"] = "IS"
        hashMap["Ireland and Northern Ireland"] = "IE"
        hashMap["Isle of Man"] = "IM"
        hashMap["Italy"] = "IT"
        hashMap["Kosovo"] = "XK"
        hashMap["Latvia"] = "LV"
        hashMap["Liechtenstein"] = "LI"
        hashMap["Lithuania"] = "LT"
        hashMap["Luxembourg"] = "LU"
        hashMap["Macedonia"] = "MK"
        hashMap["Malta"] = "MT"
        hashMap["Moldova"] = "MD"
        hashMap["Monaco"] = "MC"
        hashMap["Montenegro"] = "ME"
        hashMap["Netherlands"] = "NL"
        hashMap["Norway"] = "NO"
        hashMap["Poland"] = "PL"
        hashMap["Portugal"] = "PO"
        hashMap["Romania"] = "RO"
        hashMap["Russian Federation"] = "RU"
        hashMap["Serbia"] = "RS"
        hashMap["Slovakia"] = "SK"
        hashMap["Slovenia"] = "SI"
        hashMap["Spain"] = "ES"
        hashMap["Sweden"] = "SE"
        hashMap["Switzerland"] = "CH"
        hashMap["Turkey"] = "TR"
        hashMap["Ukraine (with Crimea)"] = "UA"
        hashMap["United Kingdom"] = "GB"

        // Africa
        hashMap["Algeria"] = "DZ"
        hashMap["Angola"] = "AO"
        hashMap["Benin"] = "BJ"
        hashMap["Botswana"] = "BW"
        hashMap["Burkina Faso"] = "BF"
        hashMap["Burundi"] = "BI"
        hashMap["Cameroon"] = "CM"
        hashMap["Cape Verde"] = "CV"
        hashMap["Central African Republic"] = "CF"
        hashMap["Chad"] = "TD"
        hashMap["Comores"] = "KM"
        hashMap["Congo (Republic/Brazzaville)"] = "CG"
        hashMap["Congo (Democratic Republic/Kinshasa)"] = "CD"
        hashMap["Djibouti"] = "DJ"
        hashMap["Egypt"] = "EG"
        hashMap["Equatorial Guinea"] = "GQ"
        hashMap["Eritrea"] = "ER"
        hashMap["Ethiopia"] = "ET"
        hashMap["Gabon"] = "GA"
        hashMap["Ghana"] = "GH"
        hashMap["Guinea"] = "GN"
        hashMap["Guinea-Bissau"] = "GW"
        hashMap["Ivory Coast"] = "CI"
        hashMap["Kenya"] = "KE"
        hashMap["Lesotho"] = "LS"
        hashMap["Liberia"] = "LR"
        hashMap["Libya"] = "LY"
        hashMap["Madagascar"] = "MG"
        hashMap["Malawi"] = "MW"
        hashMap["Mali"] = "ML"
        hashMap["Mauritania"] = "MR"
        hashMap["Mauritius"] = "MU"
        hashMap["Morocco"] = "MA"
        hashMap["Mozambique"] = "MZ"
        hashMap["Namibia"] = "NA"
        hashMap["Niger"] = "NE"
        hashMap["Nigeria"] = "NG"
        hashMap["Rwanda"] = "RW"
        hashMap["Saint Helena, Ascension, and Tristan da Cunha"] = "SH"
        hashMap["Sao Tome and Principe"] = "ST"
        hashMap["Senegal and Gambia"] = "SN"
        hashMap["Seychelles"] = "SC"
        hashMap["Sierra Leone"] = "SL"
        hashMap["Somalia"] = "SO"
        hashMap["South Africa"] = "ZA"
        hashMap["South Sudan"] = "SS"
        hashMap["Sudan"] = "SD"
        hashMap["Swaziland"] = "SZ"
        hashMap["Tanzania"] = "TZ"
        hashMap["Togo"] = "TG"
        hashMap["Tunisia"] = "TN"
        hashMap["Uganda"] = "UG"
        hashMap["Zambia"] = "ZM"
        hashMap["Zimbabwe"] = "ZW"

        // Asia
        hashMap["Afghanistan"] = "AF"
        hashMap["Armenia"] = "AM"
        hashMap["Azerbaijan"] = "AZ"
        hashMap["Bangladesh"] = "BD"
        hashMap["Bhutan"] = "BT"
        hashMap["Cambodia"] = "KH"
        hashMap["China"] = "CN"
        hashMap["East Timor"] = "TL"
        hashMap["GCC States"] = "AE"
        hashMap["India"] = "IN"
        hashMap["Indonesia (with East Timor)"] = "ID"
        hashMap["Iran"] = "IR"
        hashMap["Iraq"] = "IQ"
        hashMap["Israel and Palestine"] = "IL"
        hashMap["Japan"] = "JP"
        hashMap["Jordan"] = "JO"
        hashMap["Kazakhstan"] = "KZ"
        hashMap["Kyrgyzstan"] = "KG"
        hashMap["Laos"] = "LA"
        hashMap["Lebanon"] = "LB"
        hashMap["Malaysia, Singapore, and Brunei"] = "MY"
        hashMap["Maldives"] = "MV"
        hashMap["Mongolia"] = "MN"
        hashMap["Myanmar (a.k.a. Burma)"] = "MM"
        hashMap["Nepal"] = "NP"
        hashMap["North Korea"] = "KP"
        hashMap["Pakistan"] = "PK"
        hashMap["Philippines"] = "PH"
        hashMap["South Korea"] = "KR"
        hashMap["Sri Lanka"] = "LK"
        hashMap["Syria"] = "SY"
        hashMap["Taiwan"] = "TW"
        hashMap["Tajikistan"] = "TJ"
        hashMap["Thailand"] = "TH"
        hashMap["Turkmenistan"] = "TM"
        hashMap["Uzbekistan"] = "UZ"
        hashMap["Vietnam"] = "VN"
        hashMap["Yemen"] = "YE"

        // Australia & Oceania
        hashMap["Australia"] = "AU"
        hashMap["Cook Islands"] = "CK"
        hashMap["Fiji"] = "FJ"
        hashMap["Île de Clipperton"] = "CP"
        hashMap["Kiribati"] = "KI"
        hashMap["Marshall Islands"] = "MH"
        hashMap["Micronesia"] = ""
        hashMap["Nauru"] = "NR"
        hashMap["New Caledonia"] = "NC"
        hashMap["New Zealand"] = "NZ"
        hashMap["Niue"] = "NU"
        hashMap["Palau"] = "PW"
        hashMap["Papua New Guinea"] = "PG"
        hashMap["Pitcairn Islands"] = "PN"
        hashMap["Polynésie française (French Polynesia)"] = "PF"
        hashMap["Samoa"] = "WS"
        hashMap["Solomon Islands"] = "SB"
        hashMap["Tokelau"] = "TK"
        hashMap["Tonga"] = "TO"
        hashMap["Tuvalu"] = "TV"
        hashMap["Vanuatu"] = "VU"
        hashMap["Wallis et Futuna"] = "WF"

        // Central America
        hashMap["Bahamas"] = "BS"
        hashMap["Belize"] = "BZ"
        hashMap["Costa Rica"] = "CR"
        hashMap["Cuba"] = "CU"
        hashMap["El Salvador"] = "SV"
        hashMap["Guatemala"] = "GT"
        hashMap["Haiti and Dominican Republic"] = "HT"
        hashMap["Honduras"] = "HN"
        hashMap["Jamaica"] = "JM"
        hashMap["Nicaragua"] = "NI"
        hashMap["Panama"] = "PA"

        // North America
        hashMap["Canada"] = "CA"
        hashMap["Greenland"] = "GL"
        hashMap["Mexico"] = "MX"
        hashMap["United States of America"] = "US"

        // South America
        hashMap["Argentina"] = "AR"
        hashMap["Bolivia"] = "BO"
        hashMap["Brazil"] = "BR"
        hashMap["Chile"] = "CL"
        hashMap["Colombia"] = "CO"
        hashMap["Ecuador"] = "EC"
        hashMap["Guyana"] = "GY"
        hashMap["Paraguay"] = "PY"
        hashMap["Peru"] = "PE"
        hashMap["Suriname"] = "SR"
        hashMap["Uruguay"] = "UY"
        hashMap["Venezuela"] = "VE"

        return hashMap[name] ?: ""
    }
}