package com.bytecause.pois.util

// Geofabrik country's name mapping.
internal object CountryNameMapping {
    fun getCountryIso(name: String): String {
        val map: Map<String, String> = mapOf(
            // Europe
            "Albania" to "AL",
            "Andorra" to "AD",
            "Austria" to "AT",
            "Azores" to "PT",
            "Belarus" to "BY",
            "Belgium" to "BE",
            "Bosnia-Herzegovina" to "BA",
            "Bulgaria" to "BG",
            "Croatia" to "HR",
            "Cyprus" to "CY",
            "Czech Republic" to "CZ",
            "Denmark" to "DK",
            "Estonia" to "EE",
            "Faroe Islands" to "FO",
            "Finland" to "FI",
            "France" to "FR",
            "Georgia" to "GE",
            "Germany" to "DE",
            "Greece" to "GR",
            "Guernsey and Jersey" to "",
            "Hungary" to "HU",
            "Iceland" to "IS",
            "Ireland and Northern Ireland" to "IE",
            "Isle of Man" to "IM",
            "Italy" to "IT",
            "Kosovo" to "XK",
            "Latvia" to "LV",
            "Liechtenstein" to "LI",
            "Lithuania" to "LT",
            "Luxembourg" to "LU",
            "Macedonia" to "MK",
            "Malta" to "MT",
            "Moldova" to "MD",
            "Monaco" to "MC",
            "Montenegro" to "ME",
            "Netherlands" to "NL",
            "Norway" to "NO",
            "Poland" to "PL",
            "Portugal" to "PO",
            "Romania" to "RO",
            "Russian Federation" to "RU",
            "Serbia" to "RS",
            "Slovakia" to "SK",
            "Slovenia" to "SI",
            "Spain" to "ES",
            "Sweden" to "SE",
            "Switzerland" to "CH",
            "Turkey" to "TR",
            "Ukraine (with Crimea)" to "UA",
            "United Kingdom" to "GB",
            // Africa
            "Algeria" to "DZ",
            "Angola" to "AO",
            "Benin" to "BJ",
            "Botswana" to "BW",
            "Burkina Faso" to "BF",
            "Burundi" to "BI",
            "Cameroon" to "CM",
            "Cape Verde" to "CV",
            "Central African Republic" to "CF",
            "Chad" to "TD",
            "Comores" to "KM",
            "Congo (Republic/Brazzaville)" to "CG",
            "Congo (Democratic Republic/Kinshasa)" to "CD",
            "Djibouti" to "DJ",
            "Egypt" to "EG",
            "Equatorial Guinea" to "GQ",
            "Eritrea" to "ER",
            "Ethiopia" to "ET",
            "Gabon" to "GA",
            "Ghana" to "GH",
            "Guinea" to "GN",
            "Guinea-Bissau" to "GW",
            "Ivory Coast" to "CI",
            "Kenya" to "KE",
            "Lesotho" to "LS",
            "Liberia" to "LR",
            "Libya" to "LY",
            "Madagascar" to "MG",
            "Malawi" to "MW",
            "Mali" to "ML",
            "Mauritania" to "MR",
            "Mauritius" to "MU",
            "Morocco" to "MA",
            "Mozambique" to "MZ",
            "Namibia" to "NA",
            "Niger" to "NE",
            "Nigeria" to "NG",
            "Rwanda" to "RW",
            "Saint Helena, Ascension, and Tristan da Cunha" to "SH",
            "Sao Tome and Principe" to "ST",
            "Senegal and Gambia" to "SN",
            "Seychelles" to "SC",
            "Sierra Leone" to "SL",
            "Somalia" to "SO",
            "South Africa" to "ZA",
            "South Sudan" to "SS",
            "Sudan" to "SD",
            "Swaziland" to "SZ",
            "Tanzania" to "TZ",
            "Togo" to "TG",
            "Tunisia" to "TN",
            "Uganda" to "UG",
            "Zambia" to "ZM",
            "Zimbabwe" to "ZW",
            // Asia
            "Afghanistan" to "AF",
            "Armenia" to "AM",
            "Azerbaijan" to "AZ",
            "Bangladesh" to "BD",
            "Bhutan" to "BT",
            "Cambodia" to "KH",
            "China" to "CN",
            "East Timor" to "TL",
            "GCC States" to "AE",
            "India" to "IN",
            "Indonesia (with East Timor)" to "ID",
            "Iran" to "IR",
            "Iraq" to "IQ",
            "Israel and Palestine" to "IL",
            "Japan" to "JP",
            "Jordan" to "JO",
            "Kazakhstan" to "KZ",
            "Kyrgyzstan" to "KG",
            "Laos" to "LA",
            "Lebanon" to "LB",
            "Malaysia, Singapore, and Brunei" to "MY",
            "Maldives" to "MV",
            "Mongolia" to "MN",
            "Myanmar (a.k.a. Burma)" to "MM",
            "Nepal" to "NP",
            "North Korea" to "KP",
            "Pakistan" to "PK",
            "Philippines" to "PH",
            "South Korea" to "KR",
            "Sri Lanka" to "LK",
            "Syria" to "SY",
            "Taiwan" to "TW",
            "Tajikistan" to "TJ",
            "Thailand" to "TH",
            "Turkmenistan" to "TM",
            "Uzbekistan" to "UZ",
            "Vietnam" to "VN",
            "Yemen" to "YE",
            // Australia & Oceania
            "Australia" to "AU",
            "Cook Islands" to "CK",
            "Fiji" to "FJ",
            "Île de Clipperton" to "CP",
            "Kiribati" to "KI",
            "Marshall Islands" to "MH",
            "Micronesia" to "",
            "Nauru" to "NR",
            "New Caledonia" to "NC",
            "New Zealand" to "NZ",
            "Niue" to "NU",
            "Palau" to "PW",
            "Papua New Guinea" to "PG",
            "Pitcairn Islands" to "PN",
            "Polynésie française (French Polynesia)" to "PF",
            "Samoa" to "WS",
            "Solomon Islands" to "SB",
            "Tokelau" to "TK",
            "Tonga" to "TO",
            "Tuvalu" to "TV",
            "Vanuatu" to "VU",
            "Wallis et Futuna" to "WF",
            // Central America
            "Bahamas" to "BS",
            "Belize" to "BZ",
            "Costa Rica" to "CR",
            "Cuba" to "CU",
            "El Salvador" to "SV",
            "Guatemala" to "GT",
            "Haiti and Dominican Republic" to "HT",
            "Honduras" to "HN",
            "Jamaica" to "JM",
            "Nicaragua" to "NI",
            "Panama" to "PA",
            // North America
            "Canada" to "CA",
            "Greenland" to "GL",
            "Mexico" to "MX",
            "United States of America" to "US",
            // South America
            "Argentina" to "AR",
            "Bolivia" to "BO",
            "Brazil" to "BR",
            "Chile" to "CL",
            "Colombia" to "CO",
            "Ecuador" to "EC",
            "Guyana" to "GY",
            "Paraguay" to "PY",
            "Peru" to "PE",
            "Suriname" to "SR",
            "Uruguay" to "UY",
            "Venezuela" to "VE"
        )

        return map[name] ?: ""
    }
}